### ISSUE TITLE
Fix itsdralltanmay's profile

### ISSUE THREAD

**Issue by ksdme** [DotSlashCommunity/hacktoberfest#54]
- The profile file is missing some key elements required for it to be Jekyll page. Please check the following template to know which parts are required. Also note that the `---`'s are necessary.

```yaml
---
# Required
layout: page
title: profile
---
```
